a = "Hello World"
b = 20
c = 20.5
d = 1j
e = ["apple", "banana", "cherry"]
f = ("apple", "banana", "cherry")
g = range(6)
h = {"name" : "John", "age" : 36}
j = {"apple", "banana", "cherry"}
k = frozenset({"apple", "banana", "cherry"})
l = True
t = b"Hello"
y = bytearray(5)
u = memoryview(bytes(5))
i = None